// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlcnkvggvasxuzeyquqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sY25rdmdndmFzeHV6ZXlxdXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjc0MTgsImV4cCI6MjA3Mzc0MzQxOH0.rIn6du82iGO9yCbYbFVpQt6saxOA262g2oQCWmHreIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});